fix: shebang

diff --git a/shell/bin/download-golden-golangci b/shell/bin/download-golden-golangci
--- a/shell/bin/download-golden-golangci
+++ b/shell/bin/download-golden-golangci
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -e
 
 # Set target directory and file
 TARGET_DIR="$HOME/.dotfiles/templates"
@@ -15,18 +16,18 @@ TEMP_FILE=$(mktemp)
 
 # Download the latest revision of the gist to the temporary file
 if ! curl -s -f -o "$TEMP_FILE" "$GIST_URL"; then
-    echo "Error downloading the gist from $GIST_URL"
-    rm -f "$TEMP_FILE"
-    exit 1
+	echo "Error downloading the gist from $GIST_URL"
+	rm -f "$TEMP_FILE"
+	exit 1
 fi
 
 # Check if the target file exists and if it's different from the downloaded file
 if [ -f "$TARGET_FILE" ] && cmp -s "$TEMP_FILE" "$TARGET_FILE"; then
-    echo "The .golangci.yml file is already up to date."
+	echo "The .golangci.yml file is already up to date."
 else
-    # Move the temporary file to the target location
-    mv "$TEMP_FILE" "$TARGET_FILE"
-    echo "Downloaded latest revision of .golangci.yml to $TARGET_FILE"
+	# Move the temporary file to the target location
+	mv "$TEMP_FILE" "$TARGET_FILE"
+	echo "Downloaded latest revision of .golangci.yml to $TARGET_FILE"
 fi
 
 # Clean up (in case the file wasn't moved)
